# PostgreSQL. Versions 9.1 and up are supported.
#
# Install the pg driver:
#   gem install pg
# On OS X with Homebrew:
#   gem install pg -- --with-pg-config=/usr/local/bin/pg_config
# On OS X with MacPorts:
#   gem install pg -- --with-pg-config=/opt/local/lib/postgresql84/bin/pg_config
# On Windows:
#   gem install pg
#       Choose the win32 build.
#       Install PostgreSQL and put its /bin directory on your path.
#
# Configure Using Gemfile
# gem 'pg'
#
default: &default
  adapter: postgresql
  encoding: utf8
  # For details on connection pooling, see rails configuration guide
  # http://guides.rubyonrails.org/configuring.html#database-pooling
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: <%= ENV.fetch("DEV_DB") { 'ENTER DEV DB VARIABLES' } %>
  username: <%= ENV.fetch("DEV_DB_USERNAME") { 'ENTER DEV DB VARIABLES' } %>
  password: <%= ENV.fetch("DEV_DB_PASSWORD") { 'ENTER DEV DB VARIABLES' } %>
  host: localhost

test:
  <<: *default
  database: <%= ENV.fetch("TEST_DB") { 'ENTER TEST DB VARIABLES' } %>
  username: <%= ENV.fetch("TEST_DB_USERNAME") { 'ENTER TEST DB VARIABLES' } %>
  password: <%= ENV.fetch("TEST_DB_PASSWORD") { 'ENTER TEST DB VARIABLES' } %>
  host: localhost


production:
  <<: *default
  database: <%= ENV.fetch("PROD_DB") { 'ENTER PROD DB VARIABLES' } %>
  username: <%= ENV.fetch("PROD_DB_USERNAME") { 'ENTER PROD DB VARIABLES' } %>
  password: <%= ENV.fetch("PROD_DB_PASSWORD") { 'ENTER PROD DB VARIABLES' } %>
  host: <%= ENV.fetch("PROD_DB_HOST") { 'ENTER PROD DB VARIABLES' } %>
  port: <%= ENV.fetch("PROD_DB_PORT") { 'ENTER PROD DB VARIABLES' } %>
